name = "3d-muzeum"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2024-11-17"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"
html_handling = "drop-trailing-slash"
not_found_handling = "single-page-application"

[dev]
port = 8787

